# Generated by Django 6.0 on 2025-12-30 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_number', models.IntegerField(help_text='Candidate Number (e.g. 1)')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('KING', 'King ( & Prince/Popular)'), ('QUEEN', 'Queen ( & Princess/Popular)'), ('MISTER', 'Mister'), ('MISS', 'Miss')], max_length=10)),
                ('vote_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('category', 'candidate_number')},
            },
        ),
        migrations.CreateModel(
            name='VoteTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.candidate')),
            ],
        ),
    ]
