# Generated by Django 6.0 on 2026-01-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='King',
            fields=[
            ],
            options={
                'verbose_name': '🤴 King Candidate',
                'verbose_name_plural': '🤴 Kings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voting.candidate',),
        ),
        migrations.CreateModel(
            name='Miss',
            fields=[
            ],
            options={
                'verbose_name': '💃 Miss Candidate',
                'verbose_name_plural': '💃 Misses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voting.candidate',),
        ),
        migrations.CreateModel(
            name='Mister',
            fields=[
            ],
            options={
                'verbose_name': '🤵 Mister Candidate',
                'verbose_name_plural': '🤵 Misters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voting.candidate',),
        ),
        migrations.CreateModel(
            name='Queen',
            fields=[
            ],
            options={
                'verbose_name': '👸 Queen Candidate',
                'verbose_name_plural': '👸 Queens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('voting.candidate',),
        ),
    ]
